package com.demo.common.model;

import com.demo.common.model.base.BaseInspic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inspic extends BaseInspic<Inspic> {
	public static final Inspic dao = new Inspic();
}
